version: '2'
services:
  web:
    build:
      context: .
      args:
        DEV: 1
    entrypoint: "/app/container/entrypoint.sh"
    command: ["devserver", "-P", "8080"]
    #command: ['gunicorn']
    #command: ['nginx']
    expose:
      - 80
      - 443
      - 8080
    ports:
      - "8080:8080"
    environment:
      GUNICORN_BIND: "0.0.0.0:8080"
